- type: job
  id: USPDSWATSquadLeader
  name: job-name-uspd-swat-squadleader
  description: job-description-uspd-swat-squadleader
  playTimeTracker: JobUSPDSWATSquadLeader
  weight: 69
  startingGear: USPDSWATSquadLeader
  alwaysUseSpawner: true
  icon: "JobIconINDSquadLeader"
  requireAdminNotify: false
  supervisors: job-supervisors-usgov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - English
    languagesUnderstood:
    - English
  - !type:AddComponentSpecial
    components:
    - type: ChatRank
      rank: BF-rank-sergeant
    - type: NpcFactionMember
      factions:
      - USPD
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - NATOCommon
  - Security
  - Brig
  - Armory
  - Command
  - Medical
  - Cargo
  - Engineering
  - Research

- type: startingGear
  id: USPDSWATSquadLeader
  equipment:
    id: USPDSWATOfficerPDA
    head: ClothingHeadHatHelmetSurplus
    ears: ClothingHeadsetAltWPS
    belt: ClothingBeltStationSecurityFilledSWAT
    jumpsuit: ClothingUniformJumpsuitUSPD
    outerClothing: ClothingOuterArmorSurplusVestKevlar
    shoes: ClothingShoesBootsJackFilled
    pocket1: FlashbangGrenadeUSM84
    pocket2: PouchFirstAidFilled
  storage:
    back:
    - ClothingMaskGasM40
    - Tourniquet
