- type: job
  id: RGFMedic
  name: job-name-rgf-medic
  description: job-description-vdv-medic
  playTimeTracker: JobRGFMedic
  weight: 75
  startingGear: RGFMedicGear
  alwaysUseSpawner: true
  icon: "JobIconPACTMedic"
  requireAdminNotify: false
  supervisors: job-supervisors-rugov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
    - Ukrainian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - VDV
    - type: ChatRank
      rank: BF-rank-corporal
    - type: SurgerySpeedModifier
      SpeedModifier: 1.65
  - !type:AddImplantSpecial
    implants: [ TrackingImplantPACTRU ]
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - Medical
  - PACTCommon
  - PACTMaintenance
  - PACTMedical
  - PACTSoldier
  - PACTArmory

- type: startingGear
  id: RGFMedicGear
  equipment:
    id: RGFMedicPDA
    ears: ClothingHeadsetAltRU
    belt: ClothingBeltMedicalEMTFilledBF14
    jumpsuit: ClothingUniformJumpsuitRUGorka
    head: ClothingHeadHatHelmetRU6b47
    eyes: ClothingEyesHudMedicalBF
    outerClothing: ClothingOuterArmorPlateCarrier6B45
    shoes: ClothingShoesBootsJackFilledRU
    gloves: ClothingHandsGlovesLatex
    suitstorage: WeaponRifleRUAK74M
    pocket1: PouchMagsLargeFilledAK74Black
    pocket2: PouchGrenadesFilledVDVScout
  inhand:
    - PaperWrittenManualCombatMedic
  storage:
    back:
    - SupplyBoxMedicalFilled
    - DefibrillatorCompactBF
    - FlashlightMilitaryAlt
    - ClothingMaskGasRussiaPMK4
    - Tourniquet
    - Zipties
    - BF14AutoInjectorStormZCapped
