- type: job
  id: RGFSquadLeader
  name: job-name-rgf-squadleader
  description: job-description-rgf-squadleader
  playTimeTracker: JobRGFSquadLeader
  weight: 78
  startingGear: RGFSquadLeaderGear
  alwaysUseSpawner: true
  icon: "JobIconPACTSquadleader"
  requireAdminNotify: true
  supervisors: job-supervisors-rugov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    - Esperanto
    languagesUnderstood:
    - Russian
    - Esperanto
    - Ukrainian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - VDV
    - type: ChatRank
      rank: BF-rank-ru-juniorsergeant
  - !type:AddImplantSpecial
    implants: [ TrackingImplantPACTRU ]
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - PACTCommon
  - PACTCommand
  - PACTMaintenance
  - PACTSoldier
  - PACTArmory

- type: startingGear
  id: RGFSquadLeaderGear
  equipment:
    id: RGFSquadLeaderPDA
    ears: ClothingHeadsetAltRU
    belt: ClothingBeltMilitaryWebbingRUFilledAK74Black
    jumpsuit: ClothingUniformJumpsuitRUGorka
    head: ClothingHeadHatHelmetRU6b47
    outerClothing: ClothingOuterArmorPlateCarrier6B45
    shoes: ClothingShoesBootsJackFilledRU
    suitstorage: WeaponRifleRUAK74M
    pocket1: PouchFirstAidFilled
    pocket2: PouchGrenadesFilledRGFRifleman
    rightarmband: ClothingArmbandThighHolsterFilledRU
  storage:
    back:
    - ArmorPlateMediumPackaged
    - BoxPinpointerUniversalPACT
    - MagazinePistolMP443
    - MagazinePistolMP443
    - FlashlightMilitaryAlt
    - ClothingMaskGasRussiaPMK4
    - SyndicateWhistle
    - Tourniquet
    - Zipties
