- type: job
  id: VDVAutomaticRifleman
  name: job-name-vdv-automatic-rifleman
  description: job-description-vdv-automatic-rifleman
  playTimeTracker: JobVDVAutomaticRifleman
  weight: 76
  startingGear: VDVAutomaticRiflemanGear
  alwaysUseSpawner: true
  icon: "JobIconPACTSupport"
  requireAdminNotify: false
  supervisors: job-supervisors-rugov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
    - Ukrainian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - VDV
    - type: ChatRank
      rank: BF-rank-corporal
  - !type:AddImplantSpecial
    implants: [ TrackingImplantPACTRU ]
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - PACTCommon
  - PACTMaintenance
  - PACTSoldier
  - PACTArmory

- type: startingGear
  id: VDVAutomaticRiflemanGear
  equipment:
    id: VDVAutomaticRiflemanPDA
    ears: ClothingHeadsetAltRU
    belt: ClothingBeltMilitaryWebbingRUFilledAK74blackdrumTracerGreen
    jumpsuit: ClothingUniformJumpsuitCamoRUEMR
    head: ClothingHeadHatHelmetRU6b47Riot
    outerClothing: ClothingOuterArmorPlateCarrier6B45Heavy
    shoes: ClothingShoesBootsJackFilledRU
    neck: ClothingNeckIFFtapeWhite
    suitstorage: WeaponRifleRURPK2016
    pocket1: PouchFirstAidFilled
    pocket2: PouchGrenadesFilledVDVSupport
    rightarmband: ClothingArmbandThighHolsterFilledRU
  storage:
    back:
    - SupplyBoxAmmoRUFilledVDV
    - MagazinePistolMP443
    - MagazinePistolMP443
    - FlashlightMilitaryAlt
    - ClothingMaskGasRussiaPMK4
    - Tourniquet
    - Zipties
